### ISSUE TITLE
Replace environment variables and filter by file name

### ISSUE THREAD

**Issue by jaulz** [dlevs/vscode-regex-robin#1]
First of all, thanks a lot for the great extension! 😊 It looks very promising and is exactly what I needed. Though, I was wondering if there is a possibility to replace environment variables within the generated link. Also, it would be cool if one could add regular expressions based on the file name (i.e. only apply rule if file name matches a given expression).

**Comment by dlevs** [comment]
Both good ideas. I've been wanting the filename filtering myself, and it would be easy to add.

Any thoughts on how the environment variable substitution would look? Maybe both of these would be valid, like in shell scripts?

- `$HOME/$1`
- `${HOME}/$1`

I've not accessed environment variables in a VSCode extension before. Is this a pattern used much elsewhere?

Looking at [the vscode docs](https://code.visualstudio.com/docs/editor/variables-reference) gives me ides for other variables that would be useful, like filename, file extension, workspace directory, etc. I'm not sure how much is possible or useful, but variables like that could come in handy when the tree view is updated to be able to display matches from all files in the workspace.

**Comment by jaulz** [comment]
Yep, I was thinking about those variables as well. When you define tasks you can also make use of them. Maybe this functionality can be reused from core?

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/configurationResolver/common/variableResolver.ts

**Comment by jaulz** [comment]
I did some further research and it seems there is no real public API at the moment. However, someone mentioned in https://github.com/microsoft/vscode/issues/46471 that he created a custom extension:
https://github.com/DominicVonk/vscode-variables/blob/main/index.js

Maybe that would work temporarily? 

And regarding your initial question I think it would be best to stick vscode's syntax: ${HOME}

**Comment by dlevs** [comment]
I like the look of that "vscode-variables" package.

That looks like the right way forward. I'd be tempted to copy [that file](https://github.com/DominicVonk/vscode-variables/blob/main/index.js) into the project so it can be edited, since I think `${lineNumber}` in Regex Robin should be the line of the regex match, not the current cursor position.

Similarly, `${relativeFile}` should be the file of the match, not the current active file. Currently, Regex Robin only deals with one file at a time, but that might not always be the case as I would like to try extending the tree view to display matches across the entire workspace in the future.

I'd happily accept a PR for this if you want to take a stab at it.

**Comment by dlevs** [comment]
I'm thinking 1 regex would do the trick:

```diff
  export function replaceMatches(
    template: string,
    matchGroups: ({ match: string } | null)[]
  ) {
    return template
-      .replace(/(?<!\\)\$(\d)/g, (match, index) => {
-        return matchGroups[Number(index)]?.match ?? "";
+      .replace(/(?<!\\)(?:\$(\d)|\$\{(.*?)\})/g, (match, variableName) => {
+        // New substitution logic in here
      })
      .replace(/\\\$/g, "$");
  }
```

Example: https://regex101.com/r/4boKBQ/1

With that regex:
- `$2` is equivalent to `${2}`, which I like as it feels consitent
- New variables can be substituted, like `${env:BLAH}` and `${lineNumber}`
- These are not substituted: `\${not matching}`, `\${11}`, `\$2`

**Comment by dlevs** [comment]
Last thought on this, the final form of this could allow us to define transforms on the variable: 

```
${2:trim()}
${2:toUpperCase()}
${2:slice(0, 10)}
${2:padStart(4, '0')}
${2:floor()}
${2:ceil()}
${2:round()}
${2:toFixed()}

// Less simple examples
${env:FOO:upperCase()}
${2:trim():upperCase():slice(0, 10)}

// Probably crazy example
${2:replace('FOO', 'bar'):replace(/(Hello) /g, '$1! ')}
```

This is a feature I've found myself wanting while using this extension.

I've not considered this syntax much or checked out how other templating languages do this kind of thing. But just thinking ahead a little to be sure the changes in my last comment don't conflict with this kind of extension in the future. 🙂 

Edit: This sounded like a fun idea, so I took a stab at [a POC for this](https://github.com/dlevs/vscode-regex-robin/compare/feature/variable-transformation?expand=1). Just the transformations; no variable substitution / env variable yet, but that would be easy to slot in there. Will tidy it up and merge it in at some point.

**Comment by jaulz** [comment]
Wow, super cool, looks really promising 😊

**Comment by jaulz** [comment]
@dlevs any chance to merge this soon? 😊

**Comment by dlevs** [comment]
Hey, could do.

I settled on something simpler that just evaluates any JS in the template string, so you can do:

- `Hello $0`
- `Hello ${$0}`
- `Hello ${$0.toUpperCase()}`
- `Hello ${Number($0).toFixed(2)}`
- `Hello ${process.env.HOME}` (env variable)
- `Hello ${workspaceRoot}` (a few other vscode variables)

It works nicely in the few places it's implemented.

But when testing it out, its usage seems limited to me. Variable replacement is not currently set up for the majority of properties, like `rule.editor[i].gutterIconPath`, where I'd find it very useful to use `${workspaceRoot}`. Adding this behaviour would require a call to `vscode.window.createTextEditorDecorationType()` per regex match on every keystroke. From what I understand, this is like creating a new CSS stylesheet on every keystroke. It sounds expensive. Rather than dig deeper, I took a break from it!

Take a look at that branch I shared. Does it cover your use case?

**Comment by jaulz** [comment]
I think it would help in my use case. My use case is about function calls with relative paths, for example:
```
render("templates/app.pug")
```

In that case I would like to link it to the actual file in Code which requires the current workspace path.

**Comment by dlevs** [comment]
That's published now - try it out!

I'll close this one. Raise a separate issue if you still need the "filter by filename" feature. I don't intend to implement that any time soon, but would accept a PR with tests. 🙂

**Comment by jaulz** [comment]
Great to hear 😊  However, unfortunately, it doesn't work right now:
```
2023-03-15 12:37:31.634 [error] Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-15 12:37:31.658 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

**Comment by dlevs** [comment]
🤦‍♂️ 

OK, it's working now!

I had used the `vsce publish` for the first time instead of just uploading a zip file on the website like I usually do, and it didn't seem to like that. Fixed now, thanks.

**Comment by jaulz** [comment]
Thanks, now I could install it but I cannot use variables:
````
    {
      "regex": "mix\\('(.*)'\\)",
      "regexFlags": { "multiline": false },
      "tree": { "group": ["Mix"], "label": "$1" },
      "languages": ["blade"],
      "editor": [
        {
          "group": 1,
          "link": "${workspaceRoot}/resources/$1"
        }
      ]
    },
```

If I remove `${workspaceRoot}` it's working again.

**Comment by dlevs** [comment]
Try this instead:
```json
"link": "${workspaceFolder}/resources/$1"
```

It turns out I didn't implement `workspaceRoot`. These are the implemented variables: https://github.com/dlevs/vscode-regex-robin/blob/main/src/compileTemplate/templateArgs.ts#L66

I had a quick google to see if I _should_ implement it, and apparently it's deprecated: https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

I'd accept a PR to add it as I'm sure `workspaceRoot` is used everywhere in the wild... 🙂

**Comment by dlevs** [comment]
Also, for debugging, you can do this:

```diff
- "link": "${workspaceRoot}/resources/$1"
+ "hoverMessage": "${workspaceRoot}/resources/$1"
```

Then on hover, you get more info, like this:

> [ERROR: workspaceRoot is not defined]/.vscode/extensions.json

**Comment by jaulz** [comment]
Super cool, works perfectly! 😊  Thanks a lot, it saves me a lot of time to navigate around!
