### ISSUE TITLE
${workspaceFolder}

### ISSUE THREAD

**Issue by madsel** [dlevs/vscode-regex-robin#5]
Hey, 
I try to use vscode-regex-robin to link files relative to ${workspaceFolder}
"regexrobin.rules": [
    {
      "regex": "Test",
      "editor": [
        { 
          "link": "${workspaceFolder}/Cfg/Appl/MotorTypes/Test.m"",
          "color": "#86899F",
          "hoverMessage": "MotorType **$0**"
        }
    ]
    }
  ]
gives me:
![image](https://github.com/dlevs/vscode-regex-robin/assets/24865279/dd161351-6f65-4ab8-8ea0-6e29cfd4c8be)

Whats am I doing wrong?

**Comment by dlevs** [comment]
I've not tested this on windows. This looks like a bug. I don't have a windows machine to dig into this, sorry. If you're interested in debugging this and submitting a PR to fix it, it would be welcomed.

`%5C` decodes to `\`, which is the file path separator Windows uses. Does it work if you replace the `/` in your example with `\`?

**Comment by dlevs** [comment]
E.g. `${workspaceFolder}\Cfg\Appl\MotorTypes\Test.m`

**Comment by Hacksaw78** [comment]
Instead of:
`"link":"${workspaceFolder}/Cfg/Appl/MotorTypes/Test.m"`
try:
`"link":"file:///${workspaceFolder}/Cfg/Appl/MotorTypes/Test.m"`

Also, handy to know: anything inside the `${ }` is evaluated as JavaScript. So you can force potential back slashes to forward slashes with:
`${workspaceFolder.replaceAll(pathSeparator,'/')}`

`pathSeparator` is one of the [predefined variables](https://code.visualstudio.com/docs/editor/variables-reference) in VSCode. 


However, prefixing the _absolute_ file reference with `file:///` was enough to fix the issue in a Windows environment for me, regardless of whether the path contained back slashes or forward slashes.

**Comment by dlevs** [comment]
Thanks for the info @Hacksaw78! I've [added this to the README](https://github.com/dlevs/vscode-regex-robin/issues/5#issuecomment-1880413812).

I wonder if we should make the extension prepend `file://` to the absolute path variables automatically. I'd want to match the VSCode default behaviour as closely as possible. But I don't have a Windows machine to experiment with this, and don't want to make breaking changes, so I'll leave it. Thanks again.

**Comment by ylazy** [comment]
Thank you @Hacksaw78, you save my life :)

relative path to the current file:
instead of
`"link": "${file}/docs/$1.md"`
use
`"link": "file:///${file}/../docs/$1.md"`
